export const TOGGLE_NAVIGATION_DRAWER = 'TOGGLE_NAVIGATION_DRAWER'
export const REPLACE_SHOW_NAVIGATION_DRAWER = 'REPLACE_SHOW_NAVIGATION_DRAWER'

export const REPLACE_PROCESSING_LOGIN = 'REPLACE_PROCESSING_LOGIN'
export const REPLACE_PROCESSING_REGISTER = 'REPLACE_PROCESSING_REGISTER'
