export const TOGGLE_NAVIGATION_DRAWER = 'TOGGLE_NAVIGATION_DRAWER'
export const REPLACE_SHOW_NAVIGATION_DRAWER = 'REPLACE_SHOW_NAVIGATION_DRAWER'

export const REPLACE_PROCESSING_LOGIN = 'REPLACE_PROCESSING_LOGIN'
export const REPLACE_PROCESSING_REGISTER = 'REPLACE_PROCESSING_REGISTER'

export const REPLACE_PROCESSING_BIND = 'REPLACE_PROCESSING_BIND'
export const REPLACE_PROCESSING_ADD = 'REPLACE_PROCESSING_ADD'
export const REPLACE_PROCESSING_UPDATE = 'REPLACE_PROCESSING_UPDATE'
export const REPLACE_PROCESSING_DELETE = 'REPLACE_PROCESSING_DELETE'
